<Query Kind="Statements">
  <Connection>
    <ID>453dabbc-e8b3-4c04-8eec-536e8e4e7b58</ID>
    <Persist>true</Persist>
    <Server>triton</Server>
    <SqlSecurity>true</SqlSecurity>
    <NoPluralization>true</NoPluralization>
    <UserName>sa</UserName>
    <Password>AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAA3XCANzX8A0+HtkxmZtXFGAAAAAACAAAAAAAQZgAAAAEAACAAAACp+sEJqJxOPz2BQ1lxRRtXH/XJirk9/kw8mJj0bPf5jQAAAAAOgAAAAAIAACAAAACZd/POK3nxMSCEaCgbVDIUSs/pSsra35l5MYJ8LGMjExAAAABDe6Hrhl+CP58Aq2DzWMGNQAAAAA6bC1RC4u17G4KQF35FDnGlInhYWmmeVWDNOqKPGjJdSaTe9PMIuov4DO+z/r3whP06rpngcdEwF0GcF80cZT0=</Password>
    <IncludeSystemObjects>true</IncludeSystemObjects>
    <Database>INSURANCEW</Database>
    <ShowServer>true</ShowServer>
  </Connection>
  <Reference>C:\Temp\EPPlus.dll</Reference>
  <Namespace>OfficeOpenXml</Namespace>
  <Namespace>OfficeOpenXml.Style</Namespace>
  <Namespace>System.Drawing</Namespace>
</Query>

var daz=DAZGVEVA_201202.Take(200);


daz.Select (x => new {
	x.ADDRESS_FULL, 
	x.Base_Description, 
	x.Base_type, 
	x.BID, 
	x.BIRTH_DATE, 
	x.CHANGED_RAION_NAME_11, 
	x.CHILD_PID_FROM_JUST, 
	x.CITY, 
	x.COMPANY_CHANGE_12, 
	x.Dagv_tar, 
	x.Dazgveva, 
	x.DEATH_DATE, 
	x.DEATH_DATE_12, 
	x.DESCRIPTION_201101, 
	x.DZVELI_dagv_tar, 
	x.DZVELI_VESTIS_KONTRAQTI, 
	x.End_Date, 
	x.ETAPI, 
	x.FAMILY_SCORE, 
	x.FID, 
	x.FIRST_NAME, 
	x.GAUQMEBIS_TARIGI, 
	x.HOME_PHONE, 
	x.ID, 
	x.LAST_NAME, 
	x.LEGAL_SCORE_DATE, 
	x.MOB_PHONE, 
	x.MONEY_BACK_FROM_IRAO, 
	x.MONEY_CHANGE_CHILDS, 
	x.MONEY_CORRECTION, 
	x.OLD_ADDRESS_FULL, 
	x.OLD_BIRTH_DATE, 
	x.OLD_CITY_201111, 
	x.OLD_FIRST_NAME, 
	x.OLD_LAST_NAME, 
	x.OLD_PID_BEFORE_CHILDS_PIDS_201103, 
	x.OLD_PID_BEFORE_JUST, 
	x.OLD_RAI_201111, 
	x.OLD_RAI_NAME_201111, 
	x.OLD_REGION_ID_201111, 
	x.OLD_VILLAGE_201111, 
	x.PARENT_PERIOD_ID, 
	x.PID, 
	x.PID_DOUBLES_AFTER_CHANGE, 
	x.PID_OLD, 
	x.PID_OLD_09, 
	x.PID_OLD_1, 
	x.POLICY_NO, 
	x.POLISIS_NOMERI, 
	x.RAI, 
	x.RAI_NAME, 
	x.RAI_NAME_OLD, 
	x.RAI_OLD, 
	x.RECORD_ADD_DATE, 
	x.REGION_ID, 
	x.SAG_DAC_ADDRESS, 
	x.SAG_DACESEBULEBA, 
	x.SAG_RAI_NAME, 
	x.SAG_RAI_TYPE, 
	x.SAG_REGION, 
	x.SAM_CLIANI_KONTRAQTEBI, 
	x.Senis, 
	x.SOURCE, 
	x.SOURCE_REC_ID, 
	x.STATUS, 
	x.Unnom, 
	x.Vauch, 
	x.VILLAGE
}).Dump();